version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  flask:
    build: .
    container_name: flask
    ports:
      - "5000:5000"
    volumes:
      - ./src:/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: .
    container_name: worker
    entrypoint: ["python", "worker.py"]
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

volumes:
  redis_data:
